backend:
  name: git-gateway
  branch: main
media_folder: assets/images
slug:
  encoding: 'ascii'
  clean_accents: true
  sanitize_replacement: '_'
collections:
  - name: 'sections'
    label: 'Sections'
    files:
      - label: 'Hero'
        name: 'hero'
        file: 'content/hero.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Publish Date', name: 'date', widget: 'datetime' }
          - { label: 'Body', name: 'body', widget: 'markdown' }